version: '3.8'

services:
  backend:
    build: .
    ports:
      - "6060:6060"
    networks:
      - backend-network

  frontend:
    build: src/main/resources
    ports:
      - "80:80"
    networks:
      - backend-network

networks:
  backend-network:

